In [3]:
import fastf1

In [4]:
session = fastf1.get_session(2024, "British", "R")

In [5]:
session.load()

core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 10)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
_api        WARNING 	Driver 21: Car data is incomplete!
_api        WARNING 	Driver  3: Car data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 21: Position data is incomplete!
_api        WARNING 	Driver  3: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '55', '27', '18', '14', '23', '22', '2', '20', '3', '16', '77', '31', '11', '24', '63', '10']

In [6]:
laps = session.laps

In [9]:
laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:59:51.778000,HAM,44,0 days 00:01:36.034000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:37.703000,...,True,Mercedes,0 days 00:58:15.512000,2024-07-07 14:03:12.541,1,2.0,False,,False,False
1,0 days 01:01:23.198000,HAM,44,0 days 00:01:31.420000,2.0,1.0,NaT,NaT,0 days 00:00:29.249000,0 days 00:00:37.314000,...,True,Mercedes,0 days 00:59:51.778000,2024-07-07 14:04:48.807,1,2.0,False,,False,True
2,0 days 01:02:54.914000,HAM,44,0 days 00:01:31.716000,3.0,1.0,NaT,NaT,0 days 00:00:29.287000,0 days 00:00:37.133000,...,True,Mercedes,0 days 01:01:23.198000,2024-07-07 14:06:20.227,1,2.0,False,,False,True
3,0 days 01:04:26.902000,HAM,44,0 days 00:01:31.988000,4.0,1.0,NaT,NaT,0 days 00:00:29.554000,0 days 00:00:37.258000,...,True,Mercedes,0 days 01:02:54.914000,2024-07-07 14:07:51.943,1,2.0,False,,False,True
4,0 days 01:05:58.579000,HAM,44,0 days 00:01:31.677000,5.0,1.0,NaT,NaT,0 days 00:00:29.469000,0 days 00:00:37.231000,...,True,Mercedes,0 days 01:04:26.902000,2024-07-07 14:09:23.931,1,2.0,False,,False,True

In [12]:
verstappen = laps[laps["Driver"] == "VER"]
verstappen.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
52,0 days 00:59:52.455000,VER,1,0 days 00:01:36.711000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:37.975000,...,True,Red Bull Racing,0 days 00:58:15.512000,2024-07-07 14:03:12.541,1,3.0,False,,False,False
53,0 days 01:01:24.228000,VER,1,0 days 00:01:31.773000,2.0,1.0,NaT,NaT,0 days 00:00:29.612000,0 days 00:00:37.222000,...,True,Red Bull Racing,0 days 00:59:52.455000,2024-07-07 14:04:49.484,1,3.0,False,,False,True
54,0 days 01:02:56.428000,VER,1,0 days 00:01:32.200000,3.0,1.0,NaT,NaT,0 days 00:00:29.672000,0 days 00:00:37.216000,...,True,Red Bull Racing,0 days 01:01:24.228000,2024-07-07 14:06:21.257,1,3.0,False,,False,True
55,0 days 01:04:28.361000,VER,1,0 days 00:01:31.933000,4.0,1.0,NaT,NaT,0 days 00:00:29.626000,0 days 00:00:37.090000,...,True,Red Bull Racing,0 days 01:02:56.428000,2024-07-07 14:07:53.457,1,3.0,False,,False,True
56,0 days 01:06:00.139000,VER,1,0 days 00:01:31.778000,5.0,1.0,NaT,NaT,0 days 00:00:29.608000,0 days 00:00:37.007000,...,True,Red Bull Racing,0 days 01:04:28.361000,2024-07-07 14:09:25.390,1,3.0,False,,False,True

In [13]:
laps["Driver"].unique()

array(['HAM', 'VER', 'NOR', 'PIA', 'SAI', 'HUL', 'STR', 'ALO', 'ALB',
       'TSU', 'SAR', 'MAG', 'RIC', 'LEC', 'BOT', 'OCO', 'PER', 'ZHO',
       'RUS'], dtype=object)

In [14]:
verstappen[
    ["LapNumber", "LapTime", "Compound", "TyreLife", "Stint"]
]

     LapNumber                LapTime      Compound  TyreLife  Stint
52         1.0 0 days 00:01:36.711000        MEDIUM       1.0    1.0
53         2.0 0 days 00:01:31.773000        MEDIUM       2.0    1.0
54         3.0 0 days 00:01:32.200000        MEDIUM       3.0    1.0
55         4.0 0 days 00:01:31.933000        MEDIUM       4.0    1.0
56         5.0 0 days 00:01:31.778000        MEDIUM       5.0    1.0
57         6.0 0 days 00:01:31.711000        MEDIUM       6.0    1.0
58         7.0 0 days 00:01:31.935000        MEDIUM       7.0    1.0
59         8.0 0 days 00:01:32.038000        MEDIUM       8.0    1.0
60         9.0 0 days 00:01:31.883000        MEDIUM       9.0    1.0
61        10.0 0 days 00:01:31.661000        MEDIUM      10.0    1.0
62        11.0 0 days 00:01:31.810000        MEDIUM      11.0    1.0
63        12.0 0 days 00:01:31.894000        MEDIUM      12.0    1.0
64        13.0 0 days 00:01:31.759000        MEDIUM      13.0    1.0
65        14.0 0 days 00:01:31.700000        MEDIUM      14.0    1.0
66        15.0 0 days 00:01:32.249000        MEDIUM      15.0    1.0
67        16.0 0 days 00:01:32.504000        MEDIUM      16.0    1.0
68        17.0 0 days 00:01:35.359000        MEDIUM      17.0    1.0
69        18.0 0 days 00:01:36.172000        MEDIUM      18.0    1.0
70        19.0 0 days 00:01:42.485000        MEDIUM      19.0    1.0
71        20.0 0 days 00:01:37.108000        MEDIUM      20.0    1.0
72        21.0 0 days 00:01:33.488000        MEDIUM      21.0    1.0
73        22.0 0 days 00:01:31.904000        MEDIUM      22.0    1.0
74        23.0 0 days 00:01:32.143000        MEDIUM      23.0    1.0
75        24.0 0 days 00:01:33.020000        MEDIUM      24.0    1.0
76        25.0 0 days 00:01:36.063000        MEDIUM      25.0    1.0
77        26.0 0 days 00:01:41.491000        MEDIUM      26.0    1.0
78        27.0 0 days 00:01:59.169000  INTERMEDIATE       1.0    2.0
79        28.0 0 days 00:01:41.176000  INTERMEDIATE       2.0    2.0
80        29.0 0 days 00:01:41.533000  INTERMEDIATE       3.0    2.0
81        30.0 0 days 00:01:42.098000  INTERMEDIATE       4.0    2.0
82        31.0 0 days 00:01:42.025000  INTERMEDIATE       5.0    2.0
83        32.0 0 days 00:01:42.538000  INTERMEDIATE       6.0    2.0
84        33.0 0 days 00:01:42.606000  INTERMEDIATE       7.0    2.0
85        34.0 0 days 00:01:42.447000  INTERMEDIATE       8.0    2.0
86        35.0 0 days 00:01:43.029000  INTERMEDIATE       9.0    2.0
87        36.0 0 days 00:01:41.958000  INTERMEDIATE      10.0    2.0
88        37.0 0 days 00:01:38.869000  INTERMEDIATE      11.0    2.0
89        38.0 0 days 00:01:35.963000  INTERMEDIATE      12.0    2.0
90        39.0 0 days 00:01:58.311000          HARD       1.0    3.0
91        40.0 0 days 00:01:30.056000          HARD       2.0    3.0
92        41.0 0 days 00:01:29.604000          HARD       3.0    3.0
93        42.0 0 days 00:01:29.472000          HARD       4.0    3.0
94        43.0 0 days 00:01:29.105000          HARD       5.0    3.0
95        44.0 0 days 00:01:29.372000          HARD       6.0    3.0
96        45.0 0 days 00:01:29.137000          HARD       7.0    3.0
97        46.0 0 days 00:01:29.543000          HARD       8.0    3.0
98        47.0 0 days 00:01:29.411000          HARD       9.0    3.0
99        48.0 0 days 00:01:28.952000          HARD      10.0    3.0
100       49.0 0 days 00:01:29.560000          HARD      11.0    3.0
101       50.0 0 days 00:01:29.286000          HARD      12.0    3.0
102       51.0 0 days 00:01:29.443000          HARD      13.0    3.0
103       52.0 0 days 00:01:29.089000          HARD      14.0    3.0

In [16]:
laps["Compound"].unique()

array(['MEDIUM', 'INTERMEDIATE', 'SOFT', 'HARD'], dtype=object)